mirandacreative/wl

- .gitignore
- wp-content/themes/MC-genesis-boilerplate/assets/js/mccoder.js
- wp-content/themes/MC-genesis-boilerplate/custom.css
- wp-content/themes/MC-genesis-boilerplate/functions.php
- wp-content/themes/MC-genesis-boilerplate/template-parts/slidemenu-top.php
- wp-content/themes/MC-genesis-boilerplate/template-parts/sticky-header.php
- wp-content/themes/MC-genesis-boilerplate/template-parts/sticky-sidebar-menu.php
- wp-content/themes/MC-genesis-boilerplate/template-parts/sticky-sidebar.php
Made edits to the styles and the front page.
> Mika wl style

- wp-content/themes/MC-genesis-boilerplate/assets/js/mccoder.js
- wp-content/themes/MC-genesis-boilerplate/custom.css
- wp-content/themes/MC-genesis-boilerplate/template-parts/slidemenu-top.php
- wp-content/themes/MC-genesis-boilerplate/template-parts/sticky-header.php
Edited Sidebar styles, added a wrapper to the logo group and added styles to align left sidebar
> Structural Fixes

- wp-content/themes/MC-genesis-boilerplate/parts/flexible/card-grid.php
I cleaned up the rollover inline javascript that changed the background color of the cards
Please enter the commit message for your changes. Lines starting
> Fixed card rollovers

- wp-content/themes/MC-genesis-boilerplate/assets/js/mccoder.js
- wp-content/themes/MC-genesis-boilerplate/custom.css
- wp-content/themes/MC-genesis-boilerplate/functions.php
- wp-content/themes/MC-genesis-boilerplate/template-parts/sticky-sidebar-menu.php
I created a rule that moves the main menu to the sidebar at 1200 pixels. you will need to load the page when window is small for it to work, you cant just resize the window.
> added main menu to mobile via jquery when window is less that 1200

- wp-content/themes/MC-genesis-boilerplate/custom.css
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/director-cards.php
also added gravity forms to plugins and styled the contact form. make sure you pull the plugin and database from stage
> Worked on contact and board pages

- wp-content/themes/MC-genesis-boilerplate/custom.css
- wp-content/themes/MC-genesis-boilerplate/parts/flex.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/accordions.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/blurb-col.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/blurb-single.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/card-grid.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/child-programs.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/color-buttons.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/director-cards.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/event-blocks.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/gallery.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/people-cards.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/resource.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/three-col-list.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/title-section.php
> Mika wl contactpage01

- wp-content/themes/MC-genesis-boilerplate/custom.css
- wp-content/themes/MC-genesis-boilerplate/functions.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/accordions.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/blurb-col.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/blurb-single.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/card-grid.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/carousel.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/child-programs.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/color-buttons.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/director-cards.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/event-blocks.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/gallery.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/people-cards.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/resource.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/search.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/three-col-list.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/title-section.php
Edited Search, Cards, and added google materials.
> Mika wl globastyles03

- wp-content/themes/MC-genesis-boilerplate/custom.css
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/card-grid.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/search.php
Search and Cards on front page.
> quick fix to card and search

- wp-content/themes/MC-genesis-boilerplate/custom.css
- wp-content/themes/MC-genesis-boilerplate/parts/flex.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/search.php
- wp-content/themes/MC-genesis-boilerplate/template-parts/hours_language_mobile.php
- wp-content/themes/MC-genesis-boilerplate/template-parts/sticky-sidebar-menu.php
Added Advanced Cusstom Fields to the connect section. Facebook and twitter need to be over written though. I am not sure how. Maybe adding the icons to css with the same classes as google materials?
> Fixed Connect Links

- wp-content/themes/MC-genesis-boilerplate/assets/js/mccoder.js
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/search.php
Made a script that deactivates the search untill keys are entered then targeted an empty Iframe below the search area that populate with results.
> Search page functionality

- wp-content/themes/MC-genesis-boilerplate/custom.css
- wp-content/themes/MC-genesis-boilerplate/parts/flex.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/event-blocks.php
- wp-content/themes/MC-genesis-boilerplate/template-parts/sticky-sidebar.php
Finished up event block and made database edits.
> Finished up event block

- wp-content/themes/MC-genesis-boilerplate/custom.css
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/color-buttons.php
Finsihed colored button styles acf
> Finished Button styles added ACF

- wp-content/themes/MC-genesis-boilerplate/custom.css
- wp-content/themes/MC-genesis-boilerplate/parts/flex.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/color-buttons.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/event-blocks.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/pdf.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/resource.php
Created and styled out pdf module. Two column. Did not add column content though.
Also added to the resource modules.
Made edits to custom .css.
> Created PDF module & Added to the Resource Modules

- wp-content/themes/MC-genesis-boilerplate/assets/js/mccoder.js
- wp-content/themes/MC-genesis-boilerplate/custom.css
added jquery in mccoder and a section of dropdown css
> added code to make a 3 level or more navigation

- wp-content/themes/MC-genesis-boilerplate/custom.css
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/accordions.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/director-cards.php
> Mika wl acf02

- wp-content/themes/MC-genesis-boilerplate/assets/js/mccoder.js
- wp-content/themes/MC-genesis-boilerplate/functions.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/gallery.php
added cdn js and css then implemented to datatoggle on the gallery.php flex module
> added ekko bootstrap lighbox http://ashleydw.github.io/lightbox/

- wp-content/themes/MC-genesis-boilerplate/custom.css
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/blurb-col.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/director-cards.php
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/people-cards.php
> Fixes from the Trello card

- wp-content/themes/MC-genesis-boilerplate/parts/flexible/search.php
the first search bar targets hidden iframe, you may need to styled
> re-added search result iframe for the library catalog search

- wp-content/themes/MC-genesis-boilerplate/assets/js/mccoder.js
- wp-content/themes/MC-genesis-boilerplate/custom.css
> added the menu code to js file and tweak astyle

- wp-content/themes/MC-genesis-boilerplate/assets/js/library-hours.js
- wp-content/themes/MC-genesis-boilerplate/assets/js/mccoder.js
- wp-content/themes/MC-genesis-boilerplate/custom.css
- wp-content/themes/MC-genesis-boilerplate/parts/flexible/search.php
- wp-content/themes/MC-genesis-boilerplate/template-parts/hours_language_mobile.php
- wp-content/themes/MC-genesis-boilerplate/template-parts/sticky-sidebar.php
Still has padding issues
Fixed strange search space
fixed some things in sticky sidebary
> Fixed library hours

- wp-content/themes/MC-genesis-boilerplate/assets/js/mccoder.js
small javascript change to truncate library board minutes
> added library board minutes truncating list

- wp-content/themes/MC-genesis-boilerplate/custom.css
- wp-content/themes/MC-genesis-boilerplate/functions.php
filter function added to functions.php, styling for breadcrumbs added to custom.css
> customized genesis breadcrumbs

- wp-content/themes/MC-genesis-boilerplate/custom.css
> css cha-cha-changes

- wp-content/themes/MC-genesis-boilerplate/assets/js/mccoder.js
mccoder js - added several languages
> added bosnian albanian and urdu polish

- wp-content/themes/MC-genesis-boilerplate/template-parts/sticky-sidebar-menu.php
added facebook and twitter links
> added social links

- wp-content/themes/MC-genesis-boilerplate/parts/flexible/search.php
- wp-content/themes/MC-genesis-boilerplate/style.css
commented out the iframe and switched the target on the form link to _blank to open in a new tab
> Mike wl catalog search to new window

- wp-content/themes/MC-genesis-boilerplate/custom.css
- wp-content/themes/MC-genesis-boilerplate/template-parts/hours_language_mobile.php
fixed list style (removed bullets from showing on the library hours on mobile)
> Mike wl library hours mobile
